# Generated by Django 4.2 on 2023-05-09 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_slotid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='outdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
